package copier;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

/**
 * Created on 07/04/15.
 *
 * @author gaugendre
 */
public class MainPanel {
    private JPanel mainPanel;
    private JTextField text1;
    private JButton copierButton;
    private JTextField text2;
    private JButton finButton;
    private JFrame belongingFrame;

    public MainPanel(JFrame belongingFrame) {
        this.belongingFrame = belongingFrame;
        copierButton.addActionListener(e -> text2.setText(text1.getText()));
        copierButton.addMouseWheelListener(e -> {
            Font f = copierButton.getFont();
            f = new Font(f.getFontName(), f.getStyle(), f.getSize() - e.getWheelRotation());
            copierButton.setFont(f);
        });
        finButton.addActionListener(e -> {
            belongingFrame.dispose();
            System.exit(0);
        });
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(5, 5, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setVisible(true);
        final JLabel label1 = new JLabel();
        label1.setFont(new Font("Droid Sans", label1.getFont().getStyle(), 25));
        label1.setIcon(new ImageIcon(getClass().getResource("/hotel1.jpg")));
        label1.setText("Hôtel méridien");
        mainPanel.add(label1, new GridConstraints(3, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setFont(new Font("Droid Sans", Font.PLAIN, 18));
        label2.setForeground(new Color(-4507085));
        label2.setText("Entrer une chaîne : ");
        mainPanel.add(label2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        text1 = new JTextField();
        text1.setBackground(new Color(-8867900));
        text1.setFont(new Font("Droid Sans", text1.getFont().getStyle(), 18));
        text1.setText("");
        mainPanel.add(text1, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        copierButton = new JButton();
        copierButton.setFont(new Font("Droid Sans", copierButton.getFont().getStyle(), 18));
        copierButton.setText("Copier");
        copierButton.setMnemonic('C');
        copierButton.setDisplayedMnemonicIndex(0);
        mainPanel.add(copierButton, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setFont(new Font("Droid Sans", Font.PLAIN, 18));
        label3.setForeground(new Color(-12436805));
        label3.setText("Voici la chaîne :");
        mainPanel.add(label3, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        text2 = new JTextField();
        text2.setBackground(new Color(-2168772));
        text2.setEditable(false);
        text2.setFocusable(false);
        text2.setFont(new Font("Droid Sans", text2.getFont().getStyle(), 18));
        text2.setText("");
        mainPanel.add(text2, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(0, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(-1, 5), null, 1, false));
        final Spacer spacer2 = new Spacer();
        mainPanel.add(spacer2, new GridConstraints(0, 0, 5, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(5, -1), null, 0, false));
        final Spacer spacer3 = new Spacer();
        mainPanel.add(spacer3, new GridConstraints(0, 4, 5, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(5, -1), null, 0, false));
        final Spacer spacer4 = new Spacer();
        mainPanel.add(spacer4, new GridConstraints(4, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(-1, 5), null, 0, false));
        finButton = new JButton();
        finButton.setFont(new Font("Droid Sans", finButton.getFont().getStyle(), 18));
        finButton.setText("Fin");
        finButton.setMnemonic('F');
        finButton.setDisplayedMnemonicIndex(0);
        mainPanel.add(finButton, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
